// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qCV8lvgRDzw41gYsl8mXUL6saezFs6A',
    appId: '1:702245157471:web:857b0a6f3c94ace254f9ea',
    messagingSenderId: '702245157471',
    projectId: 'chat-app-project-6cf2e',
    authDomain: 'chat-app-project-6cf2e.firebaseapp.com',
    storageBucket: 'chat-app-project-6cf2e.appspot.com',
    measurementId: 'G-C8K8W0W5TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzAUmQ2ZYQ0c6D18wVgUK8pVFBr-4zyU',
    appId: '1:702245157471:android:c9c16e277139e36c54f9ea',
    messagingSenderId: '702245157471',
    projectId: 'chat-app-project-6cf2e',
    storageBucket: 'chat-app-project-6cf2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCK9TJBRnRiTDwhngUnTt9hkFMyrC6-cg',
    appId: '1:702245157471:ios:77e1ac4afd37e1f154f9ea',
    messagingSenderId: '702245157471',
    projectId: 'chat-app-project-6cf2e',
    storageBucket: 'chat-app-project-6cf2e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCK9TJBRnRiTDwhngUnTt9hkFMyrC6-cg',
    appId: '1:702245157471:ios:7c91ab8038670cda54f9ea',
    messagingSenderId: '702245157471',
    projectId: 'chat-app-project-6cf2e',
    storageBucket: 'chat-app-project-6cf2e.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
